/**
 * OXI SYSEX PROTOCOL
 *
 * Created on: Jul 7, 2021
 * Author: ManuelVr
 * From: https://github.com/OXI-Instruments/OXI-Desktop/blob/main/libs/oxi/oxi_core/OXI_SYSEX_MSG.h
 */

// OXI Instruments MIDI Identifiers
const OXI_INSTRUMENTS_MIDI_ID = [0x00, 0x21, 0x5b];
const OXI_ONE_ID = [0x00, 0x01];
const OXI_ONE_BLE_ID = [0x00, 0x03];

// SYSEX CATEGORIES
export enum OXI_SYSEX_CAT {
  MSG_CAT_FW_UPDATE = 0,
  MSG_CAT_BLE = 1,
  MSG_CAT_MIDI = 2,
  MSG_CAT_SYSTEM = 3,
  MSG_CAT_ANALOG = 4, // Factory?
  MSG_CAT_PROJECT = 5,
  /* ----- */
  MSG_CAT_SIZE,
}

// MESSAGE SUB CATEGORIES - Analog
export enum OXI_SYSEX_ANALOG {
  MSG_ANAL_GOTO_CALIB = 0,
  /* ----- */
  MSG_ANAL_SIZE,
}

// MESSAGE SUB CATEGORIES - System
export enum OXI_SYSEX_SYSTEM {
  MSG_SYSTEM_SW_VERSION = 0,
  MSG_SYSTEM_HW_VERSION,
  MSG_SYSTEM_GET_CALIB_DATA,
  MSG_SYSTEM_SEND_CALIB_DATA,
  MSG_SYSTEM_SIZE,

  MSG_SYSTEM_ACK = 0x53,
  MSG_SYSTEM_NACK = 0x54,
  MSG_SYSTEM_FACTORY_TEST = 0x55,
  MSG_SYSTEM_FACTORY_TEST_NOK = 0x56,

  MSG_SYSTEM_MEM_RESET = 0x61,
  /* ----- */
}

// MESSAGE SUB CATEGORIES - Firmware Update
export enum OXI_SYSEX_FW_UPDT {
  MSG_FW_UPDT_OXI_ONE = 0x31,
  MSG_FW_UPDT_OXI_BLE = 0x32,
  MSG_FW_UPDT_OXI_SPLIT = 0x33,
  /* ----- */
  MSG_FW_UPDT_READY = 0x50,
  MSG_FW_UPDT_STARTED = 0x51, // bootloader started
  MSG_FW_UPDT_EXIT = 0x52,
  MSG_FW_UPDT_ACK = 0x53,
  MSG_FW_UPDT_NACK = 0x54,
  MSG_FW_UPDT_RESTART = 0x55,
  MSG_FW_UPDT_SEND_DATA = 0x56,
  MSG_FW_UPDT_SIZE = 0x57,
  /* ----- */
  MSG_FW_UPDT_NEXT_PACKAGE = 0x7e,
  MSG_FW_UPDT_SYSTEM_RESET = 0x7f,
}

// MESSAGE SUB CATEGORIES - BLE
export enum OXI_SYSEX_BLE {
  MSG_BLE_TURN_OFF = 0,
  MSG_BLE_TURN_ON,
  MSG_BLE_CONNECTED,
  MSG_BLE_DISCONNECTED,
  /* ----- */
  MSG_BLE_SIZE,
}

// MESSAGE SUB CATEGORIES - MIDI
export enum OXI_SYSEX_MIDI {
  MSG_MIDI_USB_THRU = 0,
  MSG_MIDI_TRS_THRU,
  /* ----- */
  MSG_MIDI_SIZE,
}

// MESSAGE SUB CATEGORIES - Project
export enum OXI_SYSEX_PROJECT {
  MSG_PROJECT_GET_PROJ_HEADER = 0,
  MSG_PROJECT_SEND_PROJ_HEADER = 1,
  MSG_PROJECT_GET_PATTERN = 2,
  MSG_PROJECT_SEND_PATTERN = 3,
  MSG_PROJECT_DELETE_PROJECT = 4,
  MSG_PROJECT_DELETE_PATTERN = 5,
  /* ----- */
  MSG_PROJECT_SIZE,

  MSG_PROJECT_ACK = 0x53,
  MSG_PROJECT_NACK = 0x54,
}
